import { useMemo, useState } from "react";
import { ACTION_STATUS, TODAY } from "../data";
import { dateLabel, money, percent, savePlan } from "../engine";
import { Avatar, Badge, Button, PageHeading, Panel, Progress } from "../ui";

const toneForSignal = (signal) => signal === "Healthy" ? "success" : signal === "Watch" || signal === "At risk" ? "warning" : "danger";
const toneForRisk = (risk) => risk === "Low" ? "success" : risk === "Medium" ? "warning" : "danger";

export function Accounts({ state, summary, selected, selectedHealth, selectedOffers, updateClient, setTab, addAction, addMeeting, selectClient }) {
  const [tab, setLocalTab] = useState("overview");
  const [meeting, setMeeting] = useState({ title: "", note: "", sentiment: "Positive" });
  const [action, setAction] = useState({ title: "", owner: selected.manager, due: TODAY, type: "Success", status: "Open" });
  const plan = useMemo(() => savePlan(selected, selectedHealth), [selected, selectedHealth]);
  function saveMeeting(event) {
    event.preventDefault();
    if (!meeting.title.trim()) return;
    addMeeting(selected.id, { ...meeting, id: `meeting-${Date.now()}`, date: TODAY });
    setMeeting({ title: "", note: "", sentiment: "Positive" });
  }
  function saveAction(event) {
    event.preventDefault();
    if (!action.title.trim()) return;
    addAction(selected.id, { ...action, id: `action-${Date.now()}` });
    setAction({ title: "", owner: selected.manager, due: TODAY, type: "Success", status: "Open" });
  }
  return <div className="page">
    <PageHeading eyebrow="Account workspace" title={selected.company} text={`${selected.service} · ${selected.tier} account · Managed by ${selected.manager}. Edit the real account signals to see health, retention, and rescue recommendations change immediately.`} action={<Button onClick={() => setTab("client")}>Open client review</Button>}/>
    <div className="account-switcher"><span>Accounts</span><div>{summary.accounts.map(({ client, health }) => <button key={client.id} className={client.id === selected.id ? "selected" : ""} onClick={() => selectClient(client.id)}><i className={toneForSignal(health.signal)}></i>{client.company}<b>{health.score}</b></button>)}</div></div>
    <section className={`account-hero ${toneForSignal(selectedHealth.signal)}`}><div><p className="eyebrow">Account health</p><h2>{selectedHealth.score}<span>/100</span></h2><p>{selectedHealth.signal} account · {selectedHealth.churnRisk} churn risk · {percent(selectedHealth.renewalProbability)} renewal probability · {selectedHealth.renewalDays} days to renewal</p><div className="hero-actions"><Button onClick={() => setLocalTab("save")}>Open save plan</Button><Button variant="outline" onClick={() => setLocalTab("activity")}>Log account activity</Button></div></div><div className="health-arc"><div><strong>{selectedHealth.score}</strong><small>health score</small><Badge tone={toneForSignal(selectedHealth.signal)}>{selectedHealth.signal}</Badge></div></div></section>
    <div className="metric-grid"><Metric label="Renewal value" value={money(selected.recurringValue)} detail={`${selectedHealth.renewalDays} days remaining`} icon="◷"/><Metric label="Renewal confidence" value={percent(selectedHealth.renewalProbability)} detail={`${selectedHealth.churnRisk} churn risk`} tone={toneForRisk(selectedHealth.churnRisk)} icon="◆"/><Metric label="User adoption" value={percent(selected.adoption)} detail={`${selected.activeUsers}/${selected.targetUsers} target users active`} tone={selected.adoption < 65 ? "warning" : "success"} icon="◉"/><Metric label="Open account actions" value={selected.actions.filter((item) => item.status !== "Done").length} detail={`${selected.openTickets} ticket${selected.openTickets === 1 ? "" : "s"} open`} tone={selected.openTickets >= 4 ? "danger" : "blue"} icon="✓"/></div>
    <div className="account-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setLocalTab("overview")}>Health drivers</button><button className={tab === "save" ? "active" : ""} onClick={() => setLocalTab("save")}>Save plan</button><button className={tab === "activity" ? "active" : ""} onClick={() => setLocalTab("activity")}>Meetings & actions</button><button className={tab === "signals" ? "active" : ""} onClick={() => setLocalTab("signals")}>Account controls</button></div>
    {tab === "overview" && <div className="account-grid"><Panel eyebrow="Health drivers" title="Why this score exists"><div className="driver-list">{selectedHealth.components.map((component) => <article key={component.label}><div><strong>{component.label}</strong><span>{component.detail}</span></div><b>{component.value}</b><Progress value={component.value} tone={component.value < 52 ? "red" : component.value < 75 ? "gold" : "green"}/></article>)}</div></Panel><Panel eyebrow="Growth & retention" title="Recommended next conversation"><div className="offer-list">{selectedOffers.length ? selectedOffers.map((offer) => <article key={offer.title}><span>↗</span><div><strong>{offer.title}</strong><p>{offer.reason}</p></div><b>{money(offer.value)}</b></article>) : <div className="empty-state"><i>✓</i><strong>Protect the existing relationship first</strong><p>A growth conversation will be more effective after the account returns to a healthier position.</p></div>}</div></Panel></div>}
    {tab === "save" && <div className="account-grid"><Panel eyebrow="Tailored recovery playbook" title="Client save plan"><div className="save-plan-list">{plan.map((item, index) => <article key={`${item.title}-${index}`}><i>{index + 1}</i><div><strong>{item.title}</strong><span>{item.owner}</span><p>{item.detail}</p></div><Button variant="outline" onClick={() => addAction(selected.id, { id: `plan-${Date.now()}-${index}`, title: item.title, owner: item.owner, due: TODAY, type: "Save plan", status: "Open" })}>Add action</Button></article>)}</div></Panel><Panel eyebrow="Immediate risk signals" title="What needs attention"><div className="signal-list">{selectedHealth.signals.map((signal, index) => <article key={`${signal.title}-${index}`} className={signal.type}><i>{signal.type === "success" ? "✓" : signal.type === "finance" ? "$" : signal.type === "support" ? "!" : "◷"}</i><div><strong>{signal.title}</strong><p>{signal.detail}</p></div></article>)}</div></Panel></div>}
    {tab === "activity" && <div className="account-grid activity-grid"><Panel eyebrow="Client meetings" title="Relationship notes"><form className="mini-form" onSubmit={saveMeeting}><label>Meeting title<input required value={meeting.title} onChange={(event) => setMeeting((current) => ({ ...current, title: event.target.value }))} placeholder="e.g. Executive value review"/></label><label>Sentiment<select value={meeting.sentiment} onChange={(event) => setMeeting((current) => ({ ...current, sentiment: event.target.value }))}><option>Positive</option><option>Neutral</option><option>Concerned</option></select></label><label className="wide-field">Meeting note<textarea rows="2" value={meeting.note} onChange={(event) => setMeeting((current) => ({ ...current, note: event.target.value }))} placeholder="What did the client say, and what must happen next?"/></label><Button type="submit">Log meeting</Button></form><div className="meeting-list">{selected.meetings.length ? selected.meetings.slice().reverse().map((item) => <article key={item.id}><span className={item.sentiment.toLowerCase()}>{item.sentiment}</span><div><strong>{item.title}</strong><small>{dateLabel(item.date)}</small><p>{item.note}</p></div></article>) : <div className="empty-state"><i>○</i><strong>No recorded meetings</strong><p>Log the next client conversation to keep relationship intelligence current.</p></div>}</div></Panel><Panel eyebrow="Account action plan" title="Owners and due dates"><form className="mini-form" onSubmit={saveAction}><label>Action title<input required value={action.title} onChange={(event) => setAction((current) => ({ ...current, title: event.target.value }))} placeholder="e.g. Send recovery update"/></label><label>Owner<input value={action.owner} onChange={(event) => setAction((current) => ({ ...current, owner: event.target.value }))}/></label><label>Due date<input type="date" value={action.due} onChange={(event) => setAction((current) => ({ ...current, due: event.target.value }))}/></label><label>Type<select value={action.type} onChange={(event) => setAction((current) => ({ ...current, type: event.target.value }))}><option>Success</option><option>Save plan</option><option>Renewal</option><option>Upsell</option><option>Finance</option></select></label><Button type="submit">Add action</Button></form><div className="action-list">{selected.actions.slice().sort((a, b) => a.due.localeCompare(b.due)).map((item) => <article key={item.id}><button className={item.status === "Done" ? "done" : ""} onClick={() => updateClient(selected.id, { actions: selected.actions.map((actionItem) => actionItem.id === item.id ? { ...actionItem, status: actionItem.status === "Done" ? "Open" : "Done" } : actionItem) })}>{item.status === "Done" ? "✓" : "○"}</button><div><strong>{item.title}</strong><small>{item.owner} · due {dateLabel(item.due)} · {item.type}</small></div><Badge tone={item.status === "Done" ? "success" : "warning"}>{item.status}</Badge></article>)}</div></Panel></div>}
    {tab === "signals" && <Panel eyebrow="Editable account signals" title="Update the facts driving health"><div className="controls-grid"><label>Schedule status<select value={selected.scheduleStatus} onChange={(event) => updateClient(selected.id, { scheduleStatus: event.target.value })}><option>On track</option><option>At risk</option><option>Delayed</option></select></label><label>Delivery delay days<input type="number" min="0" value={selected.delayDays} onChange={(event) => updateClient(selected.id, { delayDays: Number(event.target.value) || 0 })}/></label><label>Open tickets<input type="number" min="0" value={selected.openTickets} onChange={(event) => updateClient(selected.id, { openTickets: Number(event.target.value) || 0 })}/></label><label>Critical tickets<input type="number" min="0" value={selected.criticalTickets} onChange={(event) => updateClient(selected.id, { criticalTickets: Number(event.target.value) || 0 })}/></label><label>Overdue invoices<input type="number" min="0" value={selected.overdueInvoices} onChange={(event) => updateClient(selected.id, { overdueInvoices: Number(event.target.value) || 0 })}/></label><label>Invoice balance<input type="number" min="0" value={selected.invoiceBalance} onChange={(event) => updateClient(selected.id, { invoiceBalance: Number(event.target.value) || 0 })}/></label><label>Client satisfaction / 10<input type="number" min="0" max="10" value={selected.satisfaction} onChange={(event) => updateClient(selected.id, { satisfaction: Number(event.target.value) || 0 })}/></label><label>Last meaningful contact<input type="date" value={selected.lastContact} onChange={(event) => updateClient(selected.id, { lastContact: event.target.value })}/></label><label>Pending approvals<input type="number" min="0" value={selected.pendingApprovals} onChange={(event) => updateClient(selected.id, { pendingApprovals: Number(event.target.value) || 0 })}/></label><label>Adoption %<input type="number" min="0" max="100" value={selected.adoption} onChange={(event) => updateClient(selected.id, { adoption: Number(event.target.value) || 0 })}/></label></div><p className="hint">Every change is saved locally and recalculates the health, renewal, churn, expansion, and save-plan recommendations instantly.</p></Panel>}
  </div>;
}
