import { clientSafeReview, dateLabel } from "../engine";
import { Badge, Button, PageHeading, Panel, Progress } from "../ui";

export function ClientReview({ selected, selectedHealth, selectedOffers, setTab }) {
  const review = clientSafeReview(selected, selectedHealth, selectedOffers);
  return <div className="page client-page">
    <PageHeading eyebrow="Client-safe experience" title="Account review portal" text="A polished client-facing review that shows progress, next priorities, and future value without exposing private health scores, churn calculations, team workloads, or internal financial information." action={<Button variant="outline" onClick={() => setTab("account")}>Back to internal account</Button>}/>
    <div className="client-shell"><section className="review-letter"><header><div className="review-brand"><span>E</span><div><small>Elite Era Development L.L.C</small><strong>Account Review</strong></div></div><Badge tone="success">Active partnership</Badge></header><div className="review-intro"><p>Prepared for {selected.company}</p><h2>Your account review</h2><p>{review.relationship}</p></div><div className="client-kpis"><article><span>Service</span><strong>{review.service}</strong><small>Current Elite Era partnership</small></article><article><span>Project progress</span><strong>{review.progress}</strong><small>Current delivery progress</small></article><article><span>Next review</span><strong>{selectedHealth.renewalDays <= 90 ? "Renewal planning" : "Roadmap planning"}</strong><small>{review.renewal}</small></article></div><Panel eyebrow="Current focus" title="What happens next"><div className="client-focus"><span>✓ Continue current milestone delivery and account support</span><span>✓ Keep shared priorities and approvals moving</span><span>✓ Schedule the next value and roadmap review</span></div></Panel><div className="client-highlight"><strong>Latest account milestone</strong><p>{review.nextMilestone}</p></div>{review.recommendation && <div className="client-opportunity"><span>Future value opportunity</span><h3>{review.recommendation.title}</h3><p>{review.recommendation.reason}</p><Button>Discuss this roadmap option</Button></div>}<footer>Made by Hira Khyzer · Elite Era Development L.L.C · #f4af00</footer></section><aside className="client-side"><Panel eyebrow="Partnership timeline" title="Recent activity"><div className="client-timeline">{selected.timeline.slice().reverse().map((item) => <article key={`${item.date}-${item.type}`}><i>{item.type === "Risk" || item.type === "Support" ? "!" : item.type === "Meeting" ? "◉" : "✓"}</i><div><strong>{item.type}</strong><small>{dateLabel(item.date)}</small><p>{item.text}</p></div></article>)}</div></Panel><Panel eyebrow="Your Elite Era team" title="Account support"><div className="client-team"><span><b>Account manager</b><strong>{selected.manager}</strong></span><span><b>Service</b><strong>{selected.service}</strong></span><span><b>Partnership started</b><strong>{dateLabel(selected.started)}</strong></span><Progress value={selected.projectProgress} tone="green"/></div></Panel></aside></div>
  </div>;
}
