import { money, percent } from "../engine";
import { Badge, Button, Metric, PageHeading, Panel, Progress } from "../ui";

const healthTone = (health) => health.signal === "Healthy" ? "success" : health.signal === "Watch" ? "warning" : health.signal === "At risk" ? "warning" : "danger";
const churnTone = (risk) => risk === "Low" ? "success" : risk === "Medium" ? "warning" : "danger";

export function Dashboard({ summary, selected, selectedHealth, setTab, selectClient }) {
  const atRisk = summary.atRisk[0] || summary.accounts.find(({ health }) => health.churnRisk !== "Low") || summary.accounts[0];
  return <div className="page">
    <PageHeading eyebrow="Elite Era Development L.L.C" title="Client health command center" text="Protect retention revenue by seeing account risk, renewal timing, relationship signals, and expansion opportunities before they become surprises." action={<Button onClick={() => setTab("accounts")}>Review client portfolio</Button>}/>
    <section className="radar-hero"><div><p className="eyebrow">Portfolio health</p><h2>{summary.healthy} of {summary.accounts.length} accounts are healthy</h2><p>{summary.atRisk.length} account{summary.atRisk.length === 1 ? " needs" : "s need"} a save plan. {summary.renewals.length} renewal{summary.renewals.length === 1 ? " is" : "s are"} within the next 90 days.</p><div className="hero-actions"><Button onClick={() => { selectClient(atRisk.client.id); setTab("account"); }}>Open highest-risk account →</Button><Button variant="outline" onClick={() => setTab("renewals")}>Plan renewals</Button></div></div><div className="radar-orb"><div><strong>{Math.round(summary.accounts.reduce((sum, item) => sum + item.health.score, 0) / summary.accounts.length)}</strong><span>average health</span><Badge tone={summary.atRisk.length ? "warning" : "success"}>{summary.atRisk.length ? "Portfolio watch" : "Portfolio healthy"}</Badge></div></div></section>
    <div className="metric-grid"><Metric label="Renewal value at stake" value={money(summary.renewalValue)} detail={`${summary.renewals.length} upcoming renewal accounts`} icon="◷"/><Metric label="Predicted renewal value" value={money(summary.predictedRenewal)} detail="Probability-adjusted forecast" tone="success" icon="◆"/><Metric label="At-risk accounts" value={summary.atRisk.length} detail="High churn or critical health signal" tone={summary.atRisk.length ? "danger" : "blue"} icon="!"/><Metric label="Expansion pipeline" value={money(summary.expansionPipeline)} detail="Recommended client-success offers" tone="ink" icon="↗"/></div>
    <div className="dashboard-grid"><Panel eyebrow="Account attention queue" title="Protect these relationships first"><div className="attention-list">{summary.accounts.slice().sort((a, b) => a.health.score - b.health.score).map(({ client, health }) => <button key={client.id} onClick={() => { selectClient(client.id); setTab("account"); }}><i className={healthTone(health)}>●</i><div><strong>{client.company}</strong><small>{health.score}/100 health · {health.churnRisk} churn risk · renewal in {health.renewalDays} days</small></div><Badge tone={healthTone(health)}>{health.signal}</Badge><span>→</span></button>)}</div></Panel><Panel eyebrow="Highest priority" title={atRisk.client.company}><div className="priority-card"><div className="priority-top"><Badge tone={healthTone(atRisk.health)}>{atRisk.health.signal}</Badge><span>{atRisk.health.churnRisk} churn risk</span></div><h3>{atRisk.health.score}/100 health score</h3><p>{atRisk.health.signals[0]?.detail}</p><div className="priority-stats"><span>Renewal <b>{atRisk.health.renewalDays} days</b></span><span>Value <b>{money(atRisk.client.recurringValue)}</b></span><span>Probability <b>{percent(atRisk.health.renewalProbability)}</b></span></div><Progress value={atRisk.health.score} tone={atRisk.health.score < 52 ? "red" : "gold"}/><Button variant="outline" onClick={() => { selectClient(atRisk.client.id); setTab("account"); }}>Open account review</Button></div></Panel></div>
    <div className="dashboard-grid"><Panel eyebrow="Renewal radar" title="Accounts to start now"><div className="renewal-list">{summary.renewals.slice().sort((a, b) => a.health.renewalDays - b.health.renewalDays).map(({ client, health }) => <article key={client.id}><div><strong>{client.company}</strong><small>{client.manager} · {health.renewalDays} days to renewal</small></div><span><b>{money(client.recurringValue)}</b><small>{percent(health.renewalProbability)} likely</small></span><Badge tone={churnTone(health.churnRisk)}>{health.churnRisk} risk</Badge></article>)}</div><Button variant="outline" onClick={() => setTab("renewals")}>Open renewal board</Button></Panel><Panel eyebrow="Expansion signal" title="Growth opportunities"><div className="opportunity-list">{summary.accounts.flatMap(({ client, offers }) => offers.slice(0, 1).map((offer) => ({ client, offer }))).slice(0, 4).map(({ client, offer }) => <article key={`${client.id}-${offer.title}`}><div><span className="mini-avatar">{client.initials}</span><div><strong>{client.company}</strong><small>{offer.title}</small></div></div><b>{money(offer.value)}</b></article>)}</div></Panel></div>
  </div>;
}
