import { dateLabel, money, percent } from "../engine";
import { Badge, Button, PageHeading, Panel, Progress } from "../ui";

const tone = (risk) => risk === "Low" ? "success" : risk === "Medium" ? "warning" : "danger";

export function Renewals({ summary, selected, selectClient, setTab, addAction }) {
  return <div className="page">
    <PageHeading eyebrow="Retention revenue planning" title="Renewal and expansion radar" text="Bring the renewal conversation forward while trust is high, and ensure unstable accounts have a recovery plan before commercial terms are discussed."/>
    <div className="renewal-metrics"><Panel eyebrow="Forecast" title="Upcoming renewal forecast"><div className="forecast-lines"><span>Renewals within 90 days <b>{money(summary.renewalValue)}</b></span><span>Probability-adjusted renewal forecast <b>{money(summary.predictedRenewal)}</b></span><span>Expansion opportunity pipeline <b>{money(summary.expansionPipeline)}</b></span></div><div className="forecast-note"><i>◆</i><p>Priority: protect {money(summary.renewalValue)} in renewal value before adding new scope to the portfolio.</p></div></Panel><Panel eyebrow="Decision rule" title="Recommended timing"><div className="timing-rules"><span><b>90–61 days</b> Confirm executive outcomes and renewal process</span><span><b>60–31 days</b> Present renewal options and roadmap</span><span><b>30–0 days</b> Close agreement or activate recovery escalation</span><span><b>High churn</b> Stabilize trust before pricing the renewal</span></div></Panel></div>
    <Panel eyebrow="Renewal pipeline" title="Accounts approaching renewal" text="Sorts accounts by the next renewal date. The health score and risk signals determine the recommended renewal posture."><div className="renewal-board">{summary.accounts.slice().sort((a, b) => a.health.renewalDays - b.health.renewalDays).map(({ client, health, offers }) => <article key={client.id}><div className="renewal-company"><span className="company-mark">{client.initials}</span><div><strong>{client.company}</strong><small>{client.service} · {client.tier} · {client.manager}</small></div></div><div><span>Renewal date</span><b>{dateLabel(client.renewalDate)}</b><small>{health.renewalDays} days remaining</small></div><div><span>Recurring value</span><b>{money(client.recurringValue)}</b><small>{percent(health.renewalProbability)} likely</small></div><div className="renewal-health"><Badge tone={tone(health.churnRisk)}>{health.churnRisk} churn</Badge><Progress value={health.score} tone={health.score < 52 ? "red" : health.score < 75 ? "gold" : "green"}/><small>{health.score}/100 health</small></div><div className="renewal-action"><strong>{health.churnRisk === "High" ? "Run save plan" : health.renewalDays <= 45 ? "Start renewal offer" : "Schedule value review"}</strong><small>{offers[0]?.title || "Account health review"}</small><div><Button onClick={() => { addAction(client.id, { id: `renewal-${Date.now()}`, title: health.churnRisk === "High" ? "Run executive save-plan review" : "Prepare renewal value review", owner: client.manager, due: client.renewalDate, type: "Renewal", status: "Open" }); selectClient(client.id); setTab("account"); }}>Create action</Button><Button variant="outline" onClick={() => { selectClient(client.id); setTab("account"); }}>Review</Button></div></div></article>)}</div></Panel>
    <div className="renewal-grid"><Panel eyebrow="High-confidence expansion" title="Where to add strategic value"><div className="expansion-board">{summary.accounts.filter(({ health }) => health.expansionScore >= 65).map(({ client, health, offers }) => <article key={client.id}><div><strong>{client.company}</strong><Badge tone="success">{health.expansionScore}/100 expansion signal</Badge></div><p>{offers[0]?.reason || "Strong adoption and account health support a roadmap conversation."}</p><span>{offers[0]?.title || "Roadmap review"}</span><b>{money(offers[0]?.value || 0)}</b></article>)}</div></Panel><Panel eyebrow="Retention risk" title="Accounts needing executive attention"><div className="risk-watch">{summary.atRisk.map(({ client, health }) => <article key={client.id}><i>!</i><div><strong>{client.company}</strong><small>{health.score}/100 health · {health.renewalDays} days to renewal · {money(client.recurringValue)} recurring value</small><p>{health.signals[0]?.title}</p></div><Button variant="outline" onClick={() => { selectClient(client.id); setTab("account"); }}>Open</Button></article>)}</div></Panel></div>
  </div>;
}
