import { dateLabel, money, percent } from "../engine";
import { Badge, Button, Metric, PageHeading, Panel } from "../ui";

const tone = (signal) => signal === "Healthy" ? "success" : signal === "Critical" ? "danger" : "warning";

export function Reports({ state, selected, selectedHealth, selectedOffers, saveReport, removeReport, exportText, exportJson, resetWorkspace }) {
  return <div className="page">
    <PageHeading eyebrow="Client success governance" title="Reports and retention records" text="Save a health snapshot before an executive account review, renewal discussion, rescue plan, or expansion proposal." action={<Button onClick={saveReport}>Save current account report</Button>}/>
    <div className="metric-grid"><Metric label="Health score" value={`${selectedHealth.score}/100`} detail={`${selectedHealth.signal} account condition`} tone={tone(selectedHealth.signal)} icon="◆"/><Metric label="Churn risk" value={selectedHealth.churnRisk} detail={`${percent(selectedHealth.renewalProbability)} renewal probability`} tone={selectedHealth.churnRisk === "Low" ? "success" : selectedHealth.churnRisk === "High" ? "danger" : "warning"} icon="!"/><Metric label="Recurring value" value={money(selected.recurringValue)} detail={`Renewal in ${selectedHealth.renewalDays} days`} icon="◷"/><Metric label="Expansion signal" value={`${selectedHealth.expansionScore}/100`} detail={selectedOffers[0]?.title || "Protect account first"} tone={selectedHealth.expansionScore >= 70 ? "success" : "blue"} icon="↗"/></div>
    <div className="report-grid"><Panel eyebrow="Export account review" title="Share a decision record"><div className="export-actions"><Button onClick={exportText}>Download TXT report</Button><Button variant="outline" onClick={exportJson}>Download JSON</Button><Button variant="outline" onClick={() => window.print()}>Print / Save as PDF</Button></div><div className="report-preview"><strong>{selected.company}</strong><span>Health: {selectedHealth.score}/100 · {selectedHealth.signal}</span><span>Churn risk: {selectedHealth.churnRisk}</span><span>Renewal confidence: {percent(selectedHealth.renewalProbability)}</span><span>Recommended action: {selectedHealth.signals[0]?.title}</span></div></Panel><Panel eyebrow="Prototype workspace" title="Data control"><p className="report-copy">Client changes, actions, meetings, and saved reports are stored only in this browser. Production deployment should use role-controlled server data.</p><Button variant="outline" onClick={resetWorkspace}>Reset demo workspace</Button><div className="report-brand"><span>Made by</span><b>Hira Khyzer</b><span>Company</span><b>Elite Era Development L.L.C</b><span>Brand color</span><b>#f4af00</b></div></Panel></div>
    <Panel eyebrow="Saved client reviews" title="Account report library" text="Keep snapshots of account condition and retention decisions over time.">{state.savedReports.length ? <div className="report-list"><div className="report-head"><span>Client</span><span>Health</span><span>Churn</span><span>Renewal confidence</span><span>Saved</span><span/></div>{state.savedReports.map((report) => <div className="report-row" key={report.id}><div><strong>{report.company}</strong><small>{report.manager}</small></div><Badge tone={tone(report.signal)}>{report.score}/100</Badge><Badge tone={report.churnRisk === "Low" ? "success" : report.churnRisk === "High" ? "danger" : "warning"}>{report.churnRisk}</Badge><span>{percent(report.renewalProbability)}</span><span>{report.createdAt}</span><button onClick={() => removeReport(report.id)}>Remove</button></div>)}</div> : <div className="empty-report"><i>▤</i><strong>No saved account reports</strong><p>Save the selected client’s health analysis before you begin a different review.</p></div>}</Panel>
    <Panel eyebrow="Account decision memo" title="Internal next steps"><div className="memo"><article><span>Current condition</span><p><b>{selectedHealth.signal}</b> — {selectedHealth.signals[0]?.detail}</p></article><article><span>Renewal posture</span><p>{selectedHealth.churnRisk === "High" ? "Stabilize the relationship and deliver recovery actions before presenting renewal pricing." : "Use outcome evidence and next-roadmap value to prepare the renewal conversation."}</p></article><article><span>Expansion posture</span><p>{selectedOffers[0] ? `${selectedOffers[0].title}: ${selectedOffers[0].reason}` : "No expansion discussion until the account health improves."}</p></article></div></Panel>
  </div>;
}
